application: languimmersion
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js/(.*\.(gif|png|jpg|js|css|json|map))$
  static_files: templates/js/\1
  upload: templates/js/.*\.(gif|png|jpg|js|css|json|map)$
- url: /sounds
  static_dir: templates/sounds
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
